name: cash_guard
description: A secure finance management application with biometric authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Локальная аутентификация (биометрия)
  local_auth: ^2.1.7

  # Безопасное хранилище данных
  flutter_secure_storage: ^9.0.0

  # Криптография для хеширования паролей
  crypto: ^3.0.3

  # Новые зависимости для backup:
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^10.3.3

  # Защита от скриншотов и записи экрана
  screen_protector: ^1.4.2

  # Для определения встряхивания устройства
  shake: ^3.0.0
  sensors_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true